FROM node:20.1.0-alpine

WORKDIR /app

# Install curl and wget if you need them in dev
RUN apk --no-cache add curl wget

# Copy package files first to leverage Docker cache
COPY package*.json ./

# Install dependencies including development ones
RUN npm install


# Expose the port the app runs on
EXPOSE 3000

# Start in development mode with the dev server
CMD ["npm", "run", "dev"]